/*
 * File: app/view/LetsMeet.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LetsMeetUp.view.LetsMeet', {
    extend: 'Ext.tab.Panel',

    config: {
        items: [
            {
                xtype: 'list',
                itemTpl: [
                    '{first}',
                    '',
                    ''
                ],
                store: 'EventStore',
                title: 'Plans',
                iconCls: 'time',
                items: [
                    {
                        xtype: 'titlebar',
                        docked: 'top',
                        title: 'Plans',
                        layout: {
                            pack: 'end',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                ui: 'confirm',
                                iconCls: 'add',
                                iconMask: true,
                                text: ''
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'navigationview',
                title: 'Friends',
                iconCls: 'team',
                items: [
                    {
                        xtype: 'list',
                        itemTpl: [
                            '{first} {last}',
                            ''
                        ],
                        store: 'FriendStore',
                        title: 'Friends'
                    }
                ]
            },
            {
                xtype: 'map',
                title: 'Nearby',
                iconCls: 'locate'
            }
        ],
        tabBar: {
            docked: 'bottom'
        }
    }

});